In [1]:
import os
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets, transforms

In [2]:
device = (
    "cuda"
    if torch.cuda.is_available()
    else "mps"
    if torch.backends.mps.is_available()
    else "cpu"
)
print(f"Using {device} device")

Using cuda device


In [3]:
# MLP model
class NeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28 * 28, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Linear(512, 10)
        )
    
    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits
    

In [6]:
model = NeuralNetwork().to(device)
print(model)

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


In [4]:
X = torch.rand(1, 28, 28, device=device)

In [7]:
logits = model(X)

In [8]:
logits

tensor([[ 0.0623, -0.0218,  0.0407, -0.0526, -0.1136,  0.0179,  0.1108,  0.0855,
          0.0303, -0.0390]], device='cuda:0', grad_fn=<AddmmBackward0>)

In [9]:
pred_probab = nn.Softmax(dim=1)(logits)

In [10]:
pred_probab

tensor([[0.1049, 0.0965, 0.1027, 0.0935, 0.0880, 0.1004, 0.1101, 0.1074, 0.1016,
         0.0948]], device='cuda:0', grad_fn=<SoftmaxBackward0>)

In [11]:
y_pred = pred_probab.argmax(1)

In [12]:
y_pred

tensor([6], device='cuda:0')