In [75]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [84]:
import numpy as np
import pandas as pd
import desicion_tree as dt
# Iris dataset
from sklearn.datasets import load_iris

# Decision tree classifier from sklearn
from sklearn.tree import DecisionTreeClassifier

iris = load_iris()

# Create a dataframe with the four feature variables
df = pd.DataFrame(iris.data, columns=iris.feature_names)

# View the top 5 rows
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [79]:
x, y = df, iris.target
x = x.to_numpy()

In [80]:
dtree = dt.DecisionTree()

In [88]:
total_e  = dtree.entropy(y)
total_e 

1.584962500721156

In [89]:
total_ev  = dtree.entropy_v(y)
total_ev 

1.584962500721156

In [93]:
x[:,0]

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9])

In [107]:
# test best_split function that takes y, number of samples and feature

bt = dtree.best_split(x, 150, x.shape[1])


feature_index:  0
feature_index:  1
feature_index:  2
feature_index:  3


In [108]:
bt

{'gain': 0.9988455359952022,
 'feature': 3,
 'threshold': 1.3,
 'left_dataset': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.

In [104]:
for f in range(x.shape[1]):
    print(f)
    print(x[:,f].shape)
    

0
(150,)
1
(150,)
2
(150,)
3
(150,)


In [74]:
n_features = x.shape[1]
best_info_gain = 0
best_feature = None
for f in range(n_features):
    print(f)
    unique_values = np.unique(x[:, f])
    new_entropy = 0
    for value in unique_values:
        y_left = y[x[:, f] == value]
        y_right = y[x[:, f] != value]

        info_gain = dtree.information_gain(y, y_left, y_right)
        new_entropy += info_gain
        print(new_entropy)

    if new_entropy > best_info_gain:
        best_info_gain = new_entropy
        best_feature = f
    
print(best_feature, best_info_gain)


0
0.01063111265619332
0.0429233488131886
0.05355446146938192
0.09688418458795489
0.11827815796913366
0.17278859375790545
0.18672735774501525
0.24788611152544293
0.31674766495245654
0.3378419642396884
0.3484730768958817
0.38728655393459577
0.422255412781825
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
2
0.01063111265619332
0.02126222531238664
0.042656198693565406
0.1199747145504082
0.2696372028725742
0.4192996911947402
0.496618207051583
0.539947930170156
0.5613419035513347
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
3
0.054510435788771794
0.43575182414726443
0.5130703400041072
0.59038885586095
0.6010199685171433
0.6116510811733367
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
None 0


m:\ML\ML_regs\decision_tree\desicion_tree.py:28: RuntimeWarning: divide by zero encountered in log2


In [45]:
x[:, 0]

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9])

In [46]:
unique_values = np.unique(x[:, 0])



In [87]:
# Create a decision tree classifier instance
clf = DecisionTreeClassifier(random_state=0)

# Fit the decision tree classifier
model = clf.fit(x, y)




array([0])

In [ ]:
"""
    Decision Tree classifier.

    Parameters
    ----------
    max_depth : int
        Maximum depth of the tree.
    min_samples_split : int
        Minimum samples in a node to consider split.
    min_impurity : float
        Minimum impurity to consider split.
    max_features : int
        Maximum number of features to consider for split.
    criterion : string
        Split criterion ("entropy" or "gini").
    random_state : int
        Random number generator seed for random weight initialization.

    Attributes
    ----------
    errors_ : list
        Number of misclassifications in every epoch.

    """

    # def __init__(self, max_depth=10, min_samples_split=2, min_impurity=1e-7,
    #              max_features=None, criterion='entropy', random_state=None):
    #     self.max_depth = max_depth
    #     self.min_samples_split = min_samples_split
    #     self.min_impurity = min_impurity
    #     self.max_features = max_features
    #     self.criterion = criterion
    #     self.random_state = random_state

    #     # initialize the root of the tree and the list of possible features
    #     self.tree = None
    #     self.feature_indices = None

    # def fit(self, X, y):
    #     """
    #     Build decision tree.

    #     Parameters
    #     ----------
    #     X : array-like, shape = [n_samples, n_features]
    #         The training input samples.
    #     y : array-like, shape = [n_samples]
    #         The target values.

    #     Returns
    #     -------
    #     self : object

    #     """
    #     # initialize tree and possible feature indices
    #     self.tree = {}
    #     self.feature_indices = np.arange(X.shape[1])

    #     # build tree
    #     self._grow_tree(X, y)

    #     return self

    # def predict(self, X):
    #     """
    #     Predict class for X.

    #     Parameters
    #     ----------
    #     X : array-like, shape = [n_samples, n_features]
    #         The input samples.

    #     Returns
    #     -------
    #     y : array of shape = [n_samples]
    #         The predicted classes.

    #     """
    #     return np.array([self._predict(inputs) for inputs in X])

    # def _grow_tree(self, X, y, depth=0):
    #     """
    #     Build decision tree.

    #     Parameters
    #     ----------
    #     X : array-like, shape = [n_samples, n_features]
    #         The training input samples.
    #     y : array-like, shape = [n_samples]
    #         The target values.
    #     depth : int
    #         Current depth in the tree.

    #     """
    #     # find the best split
    #     gain, split = self._find_split(X, y)

    #     # no (further) split if information gain is 0
    #     if gain == 0:
    #         return

    #     # split data
    #     indices_left = X[:, split] < split
    #     X_left, y_left = X[indices_left], y[indices_left]
    #     X_right, y_right = X[~indices_left], y[~indices_left]

    #     # grow left and right child
    #     depth += 1
    #     self.tree[split] = {'left': self._grow_tree(X_left, y_left, depth),
    #                         'right': self._grow_tree(X_right, y_right, depth)}

    # def _find_split(self, X, y):
    #     """
    #     Find split for the current node.

    #     Parameters
    #     ----------
    #     X : array-like, shape = [n_samples, n_features]
    #         The training input samples.
    #     y : array-like, shape = [n_samples]
    #         The target values.

    #     Returns
    #     -------
    #     gain : float
    #         Information gain.
    #     split : int
    #         Feature index of the split.

    #     """
    #     # initialize values
    #     best_gain = -1
    #     best_split = None
    #     n_samples, n_features = X.shape
    #     if self.max_features is None:
    #         self.max_features = n_features

    #     # select random features
    #     np.random.seed(self.random_state)
    #     self.feature_indices = np.random.choice(n_features, self.max_features, replace=False)

    #     # loop over all (randomly selected) features
    #     for feature in self.feature_indices:
    #         # find split
    #         split, gain = self._find_split_for_feature(X, y, feature)

    #         # update best split if information gain is higher than the current best
    #         if gain > best_gain:
    #             best_gain, best_split = gain, split

    #     return best_gain, best_split

    # def _find_split_for_feature(self, X, y, feature):
    #     """
    #     Find split for the current feature.

    #     Parameters
    #     ----------
    #     X : array-like, shape = [n_samples, n_features]
    #         The training input samples.
    #     y : array-like, shape = [n_samples]
    #         The target values.
    #     feature : int
    #         Feature index.

    #     Returns
    #     -------
    #     split : int
    #         Feature index of the split.
    #     gain : float
    #         Information gain.

    #     """
    #     # initialize values
    #     best_gain = -1
    #     split = None

    #     # loop over all possible splits
    #     for i in range(X.shape[0]):
    #         # find information gain
    #         gain = self._information_gain(y, X[:, feature], i)

    #         # update best split if information gain is higher than the current best
    #         if gain > best_gain:
    #             best_gain, split = gain, i

    #     return split, best_gain

    # def _information_gain(self, y, X_column, split):
    #     """
    #     Calculate information gain.

    #     Parameters
    #     ----------
    #     y : array-like, shape = [n_samples]
    #         The target values.
    #     X_column : array-like, shape = [n_samples]
    #         The feature values.
    #     split : int
    #         Feature index of the split.

    #     Returns
    #     -------
    #     gain : float
    #         Information gain.

    #     """
    #     # calculate parent entropy
    #     parent_entropy = self._entropy(y)

    #     # calculate weighted average of child entropy
    #     left_entropy = self._entropy(y[X_column < X_column[split]])
    #     right_entropy = self._entropy(y[X_column >= X_column[split]])
    #     child_entropy = (left_entropy * sum(X_column < X_column[split]) + right_entropy * sum(X_column >= X_column[split])) / len(y)

    #     # calculate information gain
    #     gain = parent_entropy - child_entropy

    #     return gain
        
    # def _entropy(self, y):
    #     """
    #     Calculate entropy.

    #     Parameters
    #     ----------
    #     y : array-like, shape = [n_samples]
    #         The target values.

    #     Returns
    #     -------
    #     entropy : float
    #         Entropy.

    #     """
    #     # calculate class probabilities
    #     probs = np.bincount(y) / len(y)

    #     # calculate entropy
    #     entropy = -probs.dot(np.log2(probs))

    #     return entropy

    # def _predict(self, inputs):
    #     """
    #     Predict class for inputs.

    #     Parameters
    #     ----------
    #     inputs : array-like, shape = [n_features]
    #         The input sample.

    #     Returns
    #     -------
    #     y : int
    #         The predicted class.

    #     """
    #     # loop until leaf is reached
    #     split = list(self.tree.keys())[0]
    #     while isinstance(self.tree[split], dict):
    #         split = list(self.tree[split].keys())[inputs[split] < split]

    #     return self.tree[split]
